- js/karma_get_defaults.js
- js/webpack_get_defaults.js
- mk/main.mk
- package.json
Encore une PR avec des fixups.
TODOs éventuels à discuter ! @stephane @raphael-boucher 
La question à 1000 euros est...
**COMPILE-T-ON LES LIBRARIES ?**
Jusqu'à aujourd'hui, blease-js n'avait pas la capacité de compiler des bibliothèques JS. Bluetils-js était donc livré "tel quel": uniquement le code source.
Force est de constater que dans le monde Javascript, les deux alternatives existent.
AngularJS par exemple est livré comme un fichier JS ES5 compilé, prêt à l'mploi (disons, **standalone**)
JQuery, idem. 
MomentJS est livré avec des fichiers compilés ET ses sources.
React est livré avec des choses compilées complètes et d'autres bouts d code compilés en ES5 mais plus modulaires, au choix.
Font-Awesome est livré avec soit la source SASS, soit la source LESS, soit du compilé CSS, ainsi …
> WIP: Fixups

- mk/main.mk
Old livetest is removed, since livetest is only used for debugging
> livetest-debug becomes livetest

- js/config.js
- js/webpack_get_defaults.js
- systematic.example.ini
Add new setting to set up the public path of the application (when hosted in a distinct directory).
> Configurable public path (URL)

- mk/main.mk
`npgettext` is not in the **JavaScript** default keyword list of `xgettext`, see [`‘--keyword[=keywordspec]’`](https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/xgettext-Invocation.html#Language-specific-options).
Note that Django [does the same thing](https://github.com/django/django/blob/8db889eaf7dce0cb715b075be32047c1b1b316da/django/core/management/commands/makemessages.py#L527).
> Add npgettext in the keyword list of xgettext

- README.md
- default_config/karma.conf.js
- default_config/project_path.js
- default_config/webpack.config.js
- js/karma_get_defaults.js
- mk/main.mk
Using default config files for karma and webpack allows to reduce the configuration steps for most projects.
> Default config files

- mk/main.mk
Translations strings should be extracted only when explicitly asked with `make makemessages`.
At the moment, they are extracted every time the `translations.json` file is generated, which can cause translation losses during development and unnecessary diffs in commits.
> Stop extracting strings on translations.json build

- mk/main.mk
The previous version enforced the use of ``POLYCONSEIL``; we'll now rely
on the "author" field from the "package.json" file.
> Use package author for copyright line in .po files.

- README.md
- js/config_choices.js
- js/webpack_get_defaults.js
- sample/package.json
Half an app, half a library.
Enables serving the component within a web page during the development.
Compiles a JS file with externalized CSS and no bundled dependencies during release.
> Add the "component" build type

- js/webpack_get_defaults.js
- package.json
Enables rich stuff like
```css
@import 'src/variables.css'
.myclass {
&.subclass {
color: var(--color-blue);
}
}
```
> Add support for cssnext and @import in postCSS.

- mk/main.mk
Les règles `translations` et `settings` ont pour but de générer un fichier, respectivement `$(OUTPUT_DIR)/translations.json` et `$(OUTPUT_DIR)/app.settings.js`uniquement dans le cas où leur dépendances (respectivement `$(LOCALE_FILES)` et `$(SETTINGS_INI_FILES)`) sont modifiées. Pour éviter toute regénération dans le cas où les dépendances restent inchangées, les règles `translations` et `settings` ont été adaptées pour dépendre elles-mêmes du fichier qu'elles souhaitent générer. Cette indirection est nécessaire pour vérifier par exemple que `$(OUTPUT_DIR)/translations.json` a bien été généré **après** la plus récente modification de l'une des dépendances listées dans `$(LOCALE_FILES)`. Si ce n'est pas le cas, alors `make` exécute la règle pour regénérer `$(OUTPUT_DIR)/translations.json`.
> translations & settings: Make them rebuild when necessary

- README.md
- js/config.js
- js/webpack_get_defaults.js
Some applications may be included in a web page by a web framework (e.g.
django) which is responsible for handling the hashing of its static assets.
This option enables to disable hashing for such purposes.
> add a new option to disable hashing of the bundle name

- mk/main.mk
the presence of this temp file (not temporary anymore then) causes
command makemessages not to do anything, unless using `make clean` beforehand
> main.mk: delete temp makemessages file

- CHANGES.md
- mk/main.mk
You may not even use the given host because you're behind a proxy
(integration tests) or you already opened it, or you don't even want
to open it, just run automated tests elsewhere.
> mk: don't systematically open the new instance

- js/webpack_get_defaults.js
- mk/main.mk
- mk/vue.mk
- use jsloaders within Vue files to allow for ES6 inside them.
(this disallows the use of require() inside the jsloaders, but
the string version is recommanded anyway, see babeljs.com)
- slightly make the syntax check command less verbose
> Some Vue-related fixes.

- js/webpack_get_defaults.js
see https://github.com/postcss/postcss-custom-properties#preserve
This option preserves css variables definitions. This is useful if you
want to keep the dynamic aspect of css variables. One use case is
variable overriding when including a component inside a web page.
```css
/* input */
:root {
--my-var: 16px;
}
.myClass {
margin-top: var(--my-var);
}
/* output with preserve = true */
:root {
--my-var: 16px;
}
.myClass {
margin-top: 16px;  /* for compatibility with old browsers (IE11) */
margin-top: var(--my-var);
}
/* output with preserve = false */
.myClass {
margin-top: 16px;
}
```
> webpack config: preserve css variables with css next

- mk/main.mk
Generic and suited for many purposes.
For example, it is well suited to submit a public service URL:
```
make serve SERVE_OPTIONS='--public myapp.some.domain'
```
> mk: Add a SERVE_OPTIONS variable.

- js/karma_get_defaults.js
- package.json
When running **several times in a row**(*) `make test`, this webpack plugins appears to provoke the following errors:
```
14 11 2017 10:02:33.987:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
14 11 2017 10:02:33.989:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
14 11 2017 10:02:34.006:INFO [launcher]: Starting browser ChromeHeadless
14 11 2017 10:02:34.320:INFO [HeadlessChrome 0.0.0 (Linux 0.0.0)]: Connected on socket 7cfdxPIj-lVaIP5OAAAA with id 80989099
HeadlessChrome 0.0.0 (Linux 0.0.0) ERROR
Script error.
```
or
```
✖ loadFileList
HeadlessChrome 0.0.0 (Linux 0.0.0)
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```
(*) These errors disappear when clearing module's cache: …
> For discussion: remove hard source webpack plugin ?

- js/webpack_get_defaults.js
This commit fixes a regression introduced by cfaecf1e5c8955a197.
According to the webpack doc:
-p is equivalent to --optimize-minimize --define process.env.NODE_ENV="production"
Removing the -p had the effect of preventing UglifyJS from removing Vuejs
dev mode logging. We for example had the following log in our production
bundles:
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
The --define process.env.NODE_ENV="production" can be replaced by this
commit (as advised by the vuejs official documentation).
> webpack: use DefinePlugin to pass NODE_ENV to Uglify

- CHANGES.md
- package.json
This version is required by current eslint-plugin-html version (4.0.2)
See https://github.com/BenoitZugmeyer/eslint-plugin-html#migration-to-v4
> package.json: set minimal eslint version

- mk/main.mk
Example:
make jest ARGS='-t "createTask"'
... to run only tests with a name that matches the pattern.
> makefile: Allow to pass arguments to `make test` when using Jest

- mk/main.mk
Jenkins use UTC timezone.
====
C'est pénible d'avoir les tests filio (et surement d'autres) qui plantent en local à cause des problèmes de dates.
> mk.main.mk: Force timezone to UTC for jest tests

- default_config/babelrc
These two transformers let us test with jest without getting  syntax errors on "for await (let i of myAsyncGenerator())"
====
Ce changement nous permet de passer lookcoco sous jest.
> js.babel_jest_transformer: Allow usage of async generator function with jest

- CHANGES.md
- js/webpack_get_defaults.js
- package-lock.json
- package.json
vue-loader release changelog: https://vue-loader.vuejs.org/migrating.html#template-preprocessing
vue-loader current documentation about preprocessors: https://vue-loader.vuejs.org/guide/pre-processors.html#pug
Ajout du loader pour les fichiers `.pug` et les template vuejs utilisant `lang=pug` cf le message de commit.
> webpack_get_default: add pug-plain-loader

- js/jest_get_defaults.js
- mk/main.mk
```shell
(palettone) [vperron@M]<~/dev/palettone-ui> make jenkins-test
eslint --config ./node_modules/systematic/.eslintrc --ext .js,.vue --plugin html src
JEST_JUNIT_OUTPUT='./reports/TEST-jest.xml' JEST_JUNIT_CLASSNAME="{classname}" JEST_JUNIT_TITLE="{title}" jest --ci --coverage --reporters=default --reporters=jest-junit --config=node_modules/systematic/default_config/jest.conf.js --no-cac
he             
PASS  src/pages/app.spec.js
App
✓ should export "App" (4ms)
Overview                                                              
✓ should export "Overview"
--------------------|----------|----------|----------|----------|-------------------|
File                |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s | …
```
> Add coverage options to all our tests

- mk/main.mk
easygettext supports:
- Vue files
- Javascript
- ES6
... all of which xgettext clearly doesn't have a clue.
> messages: Use easygettext for everything.

- mk/main.mk
Instead of passing shell arguments directly, the `.SHELLFLAGS` variable is now used
> Remove duplicated shell declaration

- mk/main.mk
`make makemessages` didn't search `*.vue` files anymore…
> main.mk: fix GETTEXT_SOURCES after ac7cf5e
